export const FETCH_COUNT_REQ = "FETCH_COUNT_REQ";
export const FETCH_COUNT_SUCC = "FETCH_COUNT_SUCC";
export const FETCH_COUNT_FAIL = "FETCH_COUNT_FAIL";
export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const INCREMENT_BY_AMOUNT = "INCREMENT_BY_AMOUNT";
